name: 'Generate documentation'

on:
  workflow_dispatch
env:
  node-version: 20.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - run: npm install -g @madlib-lang/madlib

      - run: |
          cd .github/workflows
          madlib install

      - run: |
          cd .github/workflows
          madlib compile --bundle -i madlib_modules/MadDocCli/src/Main.mad -o build/src/maddoc-cli.js
          node build/src/maddoc-cli.js src

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: docs
          folder: .github/workflows/.docs
